CREATE TABLE IF NOT EXISTS `Cars` (
	`car_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`vin` VARCHAR(255) NOT NULL,
	`manufacturer` VARCHAR(255) NOT NULL,
	`year` YEAR NOT NULL,
	`color` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`car_id`)
);


CREATE TABLE IF NOT EXISTS `Customers` (
	`customer_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(255) NOT NULL,
	`Phone` VARCHAR(255) NOT NULL,
	`Email` VARCHAR(255) NOT NULL,
	`Address` VARCHAR(255) NOT NULL,
	`City` VARCHAR(255) NOT NULL,
	`State_Province` VARCHAR(255) NOT NULL,
	`Country` VARCHAR(255) NOT NULL,
	`Postal_Code` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`customer_id`)
);


CREATE TABLE IF NOT EXISTS `Salespersons` (
	`salesperson_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Staff_ID` VARCHAR(255) NOT NULL,
	`Name` VARCHAR(255) NOT NULL,
	`Store` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`salesperson_id`)
);


CREATE TABLE IF NOT EXISTS `Invoices` (
	`invoice_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`car_id` BIGINT NOT NULL,
	`customer_id` BIGINT NOT NULL,
	`salesperson_id` BIGINT NOT NULL,
	PRIMARY KEY(`invoice_id`)
);


ALTER TABLE `Customers`
ADD FOREIGN KEY(`customer_id`) REFERENCES `Invoices`(`invoice_id`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `Cars`
ADD FOREIGN KEY(`car_id`) REFERENCES `Invoices`(`invoice_id`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `Salespersons`
ADD FOREIGN KEY(`salesperson_id`) REFERENCES `Invoices`(`invoice_id`)
ON UPDATE CASCADE ON DELETE CASCADE;