CREATE TABLE IF NOT EXISTS `Cars` (
	`CarID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`vin` VARCHAR(255) NOT NULL,
	`manufacturer` VARCHAR(255) NOT NULL,
	`year` YEAR NOT NULL,
	`color` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`CarID`)
);


CREATE TABLE IF NOT EXISTS `Customers` (
	`CustomerID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(255) NOT NULL,
	`Phone` VARCHAR(255) NOT NULL,
	`Email` VARCHAR(255) NOT NULL,
	`Address` VARCHAR(255) NOT NULL,
	`City` VARCHAR(255) NOT NULL,
	`State_Province` VARCHAR(255) NOT NULL,
	`Country` VARCHAR(255) NOT NULL,
	`Postal_Code` VARCHAR(255) NOT NULL,
	`` ,
	PRIMARY KEY(`CustomerID`)
);


CREATE TABLE IF NOT EXISTS `Salespersons` (
	`SalespersonID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Staff_ID` VARCHAR(255) NOT NULL,
	`Name` VARCHAR(255),
	`Store` VARCHAR(255),
	PRIMARY KEY(`SalespersonID`)
);


CREATE TABLE IF NOT EXISTS `Invoices` (
	`InvoiceID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Number` VARCHAR(255) NOT NULL,
	`Date` DATETIME NOT NULL,
	`CarID` BIGINT NOT NULL,
	`CustomerID` BIGINT NOT NULL,
	`SalespersonID` BIGINT NOT NULL,
	PRIMARY KEY(`InvoiceID`)
);


ALTER TABLE `Customers`
ADD FOREIGN KEY(`CustomerID`) REFERENCES `Invoices`(`InvoiceID`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `Cars`
ADD FOREIGN KEY(`CarID`) REFERENCES `Invoices`(`InvoiceID`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `Salespersons`
ADD FOREIGN KEY(`SalespersonID`) REFERENCES `Invoices`(`InvoiceID`)
ON UPDATE CASCADE ON DELETE CASCADE;